title: 栗崎周平
logo: https://skurizaki.github.io/homepage/Kurizaki_Nov2023.jpeg
email: kurizaki [at] waseda.jp
tagline: KURIZAKI LAB.
description: 栗崎周平<br>早稲田大学政治経済学術院・准教授<br>国立情報学研究所客員准教授<br>国立情報学研究所客員准教授<br>財務省財政総合研究所特別研究官<br>防衛省有識者会議委員<br>Editor-in-chief, Japanese Journal of Political Science
cover: /cover.jpg

categories_path: /categories/
tags_path: /tags/
