title: 栗崎周平研究室
tagline: KURIZAKI LAB.
description: 安全保障・外交・紛争解決・核戦略<br>International Security, Diplomacy, Conflict Resolution, Nuclear Strategies
cover: /cover.jpg

categories_path: /categories/
tags_path: /tags/
